pipeline {
    agent any

    tools {
        maven 'M2_HOME'
    }

    stages {
        stage('Sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube') {
    sh '''
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=ruqayyarsb_geo-app \
        -Dsonar.organization=ruqayya-saheed-baba
    '''
}
            }

        }
        stage('clean') {
            steps {
                sh 'mvn clean validate compile install test package'
            }
        }

        stage('upload artifact') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'jfrog-credentials',
                        usernameVariable: 'JFROG_USER',
                        passwordVariable: 'JFROG_PASSWORD'
                    )
                ]) {
                    sh '''
                        curl --fail -u "$JFROG_USER:$JFROG_PASSWORD" \
                        -T target/bioMedical-0.0.2-SNAPSHOT.jar \
                        ""http://ec2-3-21-43-200.us-east-2.compute.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar""
                    '''
                }
            }
        }
    }
}