pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('clean'){
            steps{ 
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:APA2kr76U8fFEdHb7sLkdhUATDu -T target/bio*.jar "http://18.227.21.122:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            } 
        } 
    } 
}